include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    top_level_function_literal_block: ignore
